### ISSUE TITLE
My osu opens, shows a window, and closed immediately. Won't open

### ISSUE THREAD

**Issue by JerryWeii-27** [Techno-coder/osu-macOS-Agent#10]
[box=Report]
Version 11.2.1 (Build 20D74)
Engine: WS11WineCX20.0.2
Wineskin 2.9.0.7-rc4
Release: Stable40
Quarantine attribute is absent (bundle)
Quarantine attribute is absent (wrapper)
Execute flag is present
Detect Direct3D is disabled
Game user configuration is absent
System Integrity Protection is disabled
Engine version is supported
Razer Synapse is absent
[Warning] Errors in: update.log
2021-02-23T08:17:26: _pending\osu!.exe => osu!.exe: FAIL
No errors in: runtime.log
[/box]
<img width="515" alt="Screen Shot 2021-02-23 at 6 30 56 PM" src="https://user-images.githubusercontent.com/79512937/108831581-4afde780-7605-11eb-9286-9216a4b749e8.png">

**Comment by JerryWeii-27** [comment]
@Techno-coder Is it possible to run it on M1 macbooks? Or do I need osu!Lazer

**Comment by Techno-coder** [comment]
Please do not report installation issues here. People have reported it working successfully on M1 processors but support is still fairly flaky. Click on Other > Update osu!. If you're still facing issues, post an issue in the help forum, not here.
