### ISSUE TITLE
Issue when opening OSU! Application

### ISSUE THREAD

**Issue by CharlieHaywood** [Techno-coder/osu-macOS-Agent#11]
Hi!

Thanks for the great work with this project! Currently, I have been able to use the Osu! Mac Agent software to repair Osu, but every time I try to open it, some application looking like terminal flashes for a second and disappears. I can't do anything else. Is there anything I can do to get Osu working again? For the record, I am on an M1 Mac.

Also, I was able to snag a screenshot of the issue that opens.
<img width="636" alt="Screenshot 2021-03-22 at 9 23 17 PM" src="https://user-images.githubusercontent.com/73516972/111996464-02c6dc00-8b55-11eb-9ccc-dab5810e9579.png">

Thanks :)

**Comment by Techno-coder** [comment]
Please see https://github.com/Techno-coder/osu-macOS-Agent/issues/10
