### ISSUE TITLE
osu!macOS Agent keeps crashing upon opening.

### ISSUE THREAD

**Issue by heiheigrandmaster** [Techno-coder/osu-macOS-Agent#12]
Hey Technocoder,

I have encountered an issue

 while trying to install the osu!macOS Agent. The application just keeps crashing / closing instantaneously after opening.

I've tried several ordinary troubleshooting methods including restarting, reinstalling, reading thoroughly through the steps on the forums, investigating its status on activity monitor etc., but nothing seemed to work. 

Please take a look at this video for reference:

https://mykeystone-my.sharepoint.com/:v:/g/personal/71162_stpeters_sa_edu_au/EfxXFRUyQqNHtrMoRWR8BqYBqrrTLqiD_Ci3jxYqj32RMA?e=UrESnq

Extra details:

- The agent opened up just fine 2 days ago when I first installed it, but when I tried to play this morning, it opened for around 3 seconds before crashing, and after that, I could not open it anymore even after troubleshooting.

- When I first opened the agent after installing, I says that it's "terminated" (as seen in the video) right after being opened.

- When I was troubleshooting, the agent only showed up on activity monitor the first time it was, but after that it never did again, until I deleted it and installed a new one from the .zip file.

- I'm pretty sure that this morning, I was trying to import new beatmaps into osu!, but forgot to tick the boxes for "auto import from downloads" the other day, so I opened it up the agent to do it, but right as I clicked on the box, it crashed.

- I installed osu! on my bootcamped windows disk (same computer) as well the day after when it worked fine (when I first installed it). Today, when I switched back to play osu! on mac, it crashed (with osu! installed on my bootcamped disk as well).

I am not sure of what to do next, and I hope you can help me find a solution to this :)

Thanks!

**Comment by Techno-coder** [comment]
Closing this as it's being handled in this thread: https://osu.ppy.sh/community/forums/topics/1347590
