### ISSUE TITLE
Problem with oppening

### ISSUE THREAD

**Issue by Mino0903** [Techno-coder/osu-macOS-Agent#13]
I have downloaded the osu agent file and it doesn't open, my computer (mac os big sur 11.6 11.6) shows error " “osu!macOS Agent” cannot be opened because the developer cannot be verified, macOS cannot verify that this app is free from malware." It only allows me to move the file to bin or leave it be. Please reply as soon as possible.

**Comment by Techno-coder** [comment]
Please follow every installation step on the forum thread: https://osu.ppy.sh/community/forums/topics/1036678. Installation issues should be posted on the main Wineskin forum thread: https://osu.ppy.sh/community/forums/topics/1106057
