### ISSUE TITLE
Language garbled problem

### ISSUE THREAD

**Issue by YYY911TTT** [Techno-coder/osu-macOS-Agent#9]
Hi I found in the game settings, trying to change the Chinese, the Japanese language will be garbled and cannot be displayed, can you fix it?

**Comment by Techno-coder** [comment]
This is an issue with the Wineskin configuration (missing fake font mappings) so while this tool could automatically fix the font mappings on a particular Wineskin I think it'd be better if the Wineskin was modified instead.

**Comment by YYY911TTT** [comment]
I tried to open Wineskin in osu.app (fixed), but an error was displayed: exec2542435495.bat doesn't exist, is there any way I can download fonts?
